apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service-deployment
  namespace: devops-platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
      - name: user-service
        image: ngcicd/user-service:v1
        envFrom:
        - configMapRef:
            name: user-service-configmap
        - secretRef:
            name: user-service-secret
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        ports:
        - containerPort: 8001
---
apiVersion: v1
kind: Service
metadata:
  name: user-service-service
  namespace: devops-platform
spec:
  selector:
    app: user-service
  type: NodePort
  ports:
  - port: 8001
    targetPort: 8001
