apiVersion: v1
kind: Secret
metadata:
  name: global-secret
  namespace: {{ .Release.Namespace }}
  
type: Opaque
data:
  POSTGRES_USER: {{.Values.global.postgres.user | b64enc}}
  POSTGRES_PASSWORD: {{.Values.global.postgres.password | b64enc}}